# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ntest.proto\"\x03\n\x01Mb\x06proto3'
)




_M = _descriptor.Descriptor(
  name='M',
  full_name='M',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=17,
)

DESCRIPTOR.message_types_by_name['M'] = _M
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

M = _reflection.GeneratedProtocolMessageType('M', (_message.Message,), {
  'DESCRIPTOR' : _M,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:M)
  })
_sym_db.RegisterMessage(M)


# @@protoc_insertion_point(module_scope)
