/* This file was generated by upbc (the upb compiler) from the input
 * file:
 *
 *     google/protobuf/descriptor.proto
 *
 * Do not edit -- your changes will be discarded when the file is
 * regenerated. */

#include <stddef.h>
#include "upb/msg.h"
#include "google/protobuf/descriptor.upb.h"

#include "upb/port_def.inc"

static const upb_msglayout *const google_protobuf_FileDescriptorSet_submsgs[1] = {
  &google_protobuf_FileDescriptorProto_msginit,
};

static const upb_msglayout_field google_protobuf_FileDescriptorSet__fields[1] = {
  {1, UPB_SIZE(0, 0), 0, 0, 11, 3},
};

const upb_msglayout google_protobuf_FileDescriptorSet_msginit = {
  &google_protobuf_FileDescriptorSet_submsgs[0],
  &google_protobuf_FileDescriptorSet__fields[0],
  UPB_SIZE(8, 8), 1, false, 1,
  {
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_prm_1bt_max192b, UPB_SIZE(-281474976710646, -281474976710646)},
  },
};

static const upb_msglayout *const google_protobuf_FileDescriptorProto_submsgs[6] = {
  &google_protobuf_DescriptorProto_msginit,
  &google_protobuf_EnumDescriptorProto_msginit,
  &google_protobuf_FieldDescriptorProto_msginit,
  &google_protobuf_FileOptions_msginit,
  &google_protobuf_ServiceDescriptorProto_msginit,
  &google_protobuf_SourceCodeInfo_msginit,
};

static const upb_msglayout_field google_protobuf_FileDescriptorProto__fields[12] = {
  {1, UPB_SIZE(4, 8), 1, 0, 12, 1},
  {2, UPB_SIZE(12, 24), 2, 0, 12, 1},
  {3, UPB_SIZE(36, 72), 0, 0, 12, 3},
  {4, UPB_SIZE(40, 80), 0, 0, 11, 3},
  {5, UPB_SIZE(44, 88), 0, 1, 11, 3},
  {6, UPB_SIZE(48, 96), 0, 4, 11, 3},
  {7, UPB_SIZE(52, 104), 0, 2, 11, 3},
  {8, UPB_SIZE(28, 56), 4, 3, 11, 1},
  {9, UPB_SIZE(32, 64), 5, 5, 11, 1},
  {10, UPB_SIZE(56, 112), 0, 0, 5, 3},
  {11, UPB_SIZE(60, 120), 0, 0, 5, 3},
  {12, UPB_SIZE(20, 40), 3, 0, 12, 1},
};

const upb_msglayout google_protobuf_FileDescriptorProto_msginit = {
  &google_protobuf_FileDescriptorProto_submsgs[0],
  &google_protobuf_FileDescriptorProto__fields[0],
  UPB_SIZE(64, 128), 12, false, 4,
  {
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_pss_1bt, UPB_SIZE(131082, 1125899906973706)},
    {&upb_pss_1bt, UPB_SIZE(2251799813947410, 5629499534475282)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_prm_1bt_max128b, UPB_SIZE(10133099161583650, 21392098230009890)},
    {&upb_prm_1bt_max128b, UPB_SIZE(11258999068491818, 23643898043760682)},
    {&upb_prm_1bt_max64b, UPB_SIZE(12384898975531058, 25895697857642546)},
    {&upb_prm_1bt_max192b, UPB_SIZE(13510798882242618, 28147497671196730)},
    {&upb_psm_1bt_max256b, UPB_SIZE(6755485340598338, 14636784688496706)},
    {&upb_psm_1bt_max64b, UPB_SIZE(7881389542539338, 16888588797280330)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_pss_1bt, UPB_SIZE(4503599627894882, 10133099162108002)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
  },
};

static const upb_msglayout *const google_protobuf_DescriptorProto_submsgs[7] = {
  &google_protobuf_DescriptorProto_msginit,
  &google_protobuf_DescriptorProto_ExtensionRange_msginit,
  &google_protobuf_DescriptorProto_ReservedRange_msginit,
  &google_protobuf_EnumDescriptorProto_msginit,
  &google_protobuf_FieldDescriptorProto_msginit,
  &google_protobuf_MessageOptions_msginit,
  &google_protobuf_OneofDescriptorProto_msginit,
};

static const upb_msglayout_field google_protobuf_DescriptorProto__fields[10] = {
  {1, UPB_SIZE(4, 8), 1, 0, 12, 1},
  {2, UPB_SIZE(16, 32), 0, 4, 11, 3},
  {3, UPB_SIZE(20, 40), 0, 0, 11, 3},
  {4, UPB_SIZE(24, 48), 0, 3, 11, 3},
  {5, UPB_SIZE(28, 56), 0, 1, 11, 3},
  {6, UPB_SIZE(32, 64), 0, 4, 11, 3},
  {7, UPB_SIZE(12, 24), 2, 5, 11, 1},
  {8, UPB_SIZE(36, 72), 0, 6, 11, 3},
  {9, UPB_SIZE(40, 80), 0, 2, 11, 3},
  {10, UPB_SIZE(44, 88), 0, 0, 12, 3},
};

const upb_msglayout google_protobuf_DescriptorProto_msginit = {
  &google_protobuf_DescriptorProto_submsgs[0],
  &google_protobuf_DescriptorProto__fields[0],
  UPB_SIZE(48, 96), 10, false, 4,
  {
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_pss_1bt, UPB_SIZE(131082, 1125899906973706)},
    {&upb_prm_1bt_max192b, UPB_SIZE(3377699720790034, 7881299348160530)},
    {&upb_prm_1bt_max128b, UPB_SIZE(4503599627370522, 10133099161583642)},
    {&upb_prm_1bt_max128b, UPB_SIZE(5629499534409762, 12384898975465506)},
    {&upb_prm_1bt_max64b, UPB_SIZE(6755399441121322, 14636698789019690)},
    {&upb_prm_1bt_max192b, UPB_SIZE(7881299348160562, 16888498602901554)},
    {&upb_psm_1bt_max64b, UPB_SIZE(2251877123424314, 5629576843952186)},
    {&upb_prm_1bt_max64b, UPB_SIZE(9007199255134274, 19140298416717890)},
    {&upb_prm_1bt_max64b, UPB_SIZE(10133099161714762, 21392098230141002)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
  },
};

static const upb_msglayout *const google_protobuf_DescriptorProto_ExtensionRange_submsgs[1] = {
  &google_protobuf_ExtensionRangeOptions_msginit,
};

static const upb_msglayout_field google_protobuf_DescriptorProto_ExtensionRange__fields[3] = {
  {1, UPB_SIZE(4, 4), 1, 0, 5, 1},
  {2, UPB_SIZE(8, 8), 2, 0, 5, 1},
  {3, UPB_SIZE(12, 16), 3, 0, 11, 1},
};

const upb_msglayout google_protobuf_DescriptorProto_ExtensionRange_msginit = {
  &google_protobuf_DescriptorProto_ExtensionRange_submsgs[0],
  &google_protobuf_DescriptorProto_ExtensionRange__fields[0],
  UPB_SIZE(16, 24), 3, false, 2,
  {
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_psv4_1bt, UPB_SIZE(562949953552392, 562949953552392)},
    {&upb_psv4_1bt, UPB_SIZE(1688849860526096, 1688849860526096)},
    {&upb_psm_1bt_max64b, UPB_SIZE(2814831371485210, 3940731278327834)},
  },
};

static const upb_msglayout_field google_protobuf_DescriptorProto_ReservedRange__fields[2] = {
  {1, UPB_SIZE(4, 4), 1, 0, 5, 1},
  {2, UPB_SIZE(8, 8), 2, 0, 5, 1},
};

const upb_msglayout google_protobuf_DescriptorProto_ReservedRange_msginit = {
  NULL,
  &google_protobuf_DescriptorProto_ReservedRange__fields[0],
  UPB_SIZE(16, 16), 2, false, 2,
  {
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_psv4_1bt, UPB_SIZE(562949953552392, 562949953552392)},
    {&upb_psv4_1bt, UPB_SIZE(1688849860526096, 1688849860526096)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
  },
};

static const upb_msglayout *const google_protobuf_ExtensionRangeOptions_submsgs[1] = {
  &google_protobuf_UninterpretedOption_msginit,
};

static const upb_msglayout_field google_protobuf_ExtensionRangeOptions__fields[1] = {
  {999, UPB_SIZE(0, 0), 0, 0, 11, 3},
};

const upb_msglayout google_protobuf_ExtensionRangeOptions_msginit = {
  &google_protobuf_ExtensionRangeOptions_submsgs[0],
  &google_protobuf_ExtensionRangeOptions__fields[0],
  UPB_SIZE(8, 8), 1, false, 0,
  {
    {&fastdecode_generic, UPB_SIZE(0, 0)},
  },
};

static const upb_msglayout *const google_protobuf_FieldDescriptorProto_submsgs[1] = {
  &google_protobuf_FieldOptions_msginit,
};

static const upb_msglayout_field google_protobuf_FieldDescriptorProto__fields[11] = {
  {1, UPB_SIZE(36, 40), 6, 0, 12, 1},
  {2, UPB_SIZE(44, 56), 7, 0, 12, 1},
  {3, UPB_SIZE(24, 24), 3, 0, 5, 1},
  {4, UPB_SIZE(8, 8), 1, 0, 14, 1},
  {5, UPB_SIZE(16, 16), 2, 0, 14, 1},
  {6, UPB_SIZE(52, 72), 8, 0, 12, 1},
  {7, UPB_SIZE(60, 88), 9, 0, 12, 1},
  {8, UPB_SIZE(76, 120), 11, 0, 11, 1},
  {9, UPB_SIZE(28, 28), 4, 0, 5, 1},
  {10, UPB_SIZE(68, 104), 10, 0, 12, 1},
  {17, UPB_SIZE(32, 32), 5, 0, 8, 1},
};

const upb_msglayout google_protobuf_FieldDescriptorProto_msginit = {
  &google_protobuf_FieldDescriptorProto_submsgs[0],
  &google_protobuf_FieldDescriptorProto__fields[0],
  UPB_SIZE(80, 128), 11, false, 5,
  {
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_pss_1bt, UPB_SIZE(8725724282224650, 9851624189067274)},
    {&upb_pss_1bt, UPB_SIZE(10977524100104210, 14355223820632082)},
    {&upb_psv4_1bt, UPB_SIZE(5348024558026776, 5348024558026776)},
    {&upb_psv4_1bt, UPB_SIZE(844424930263072, 844424930263072)},
    {&upb_psv4_1bt, UPB_SIZE(3096224744079400, 3096224744079400)},
    {&upb_pss_1bt, UPB_SIZE(13229323922178098, 18858823456391218)},
    {&upb_pss_1bt, UPB_SIZE(15481123752640570, 23362423100538938)},
    {&upb_psm_1bt_max64b, UPB_SIZE(19984839310573634, 32369738285842498)},
    {&upb_psv4_1bt, UPB_SIZE(6473924465393736, 6473924465393736)},
    {&upb_pss_1bt, UPB_SIZE(17732923599880274, 27866022761463890)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_psb1_2bt, UPB_SIZE(7599824373285256, 7599824373285256)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
  },
};

static const upb_msglayout *const google_protobuf_OneofDescriptorProto_submsgs[1] = {
  &google_protobuf_OneofOptions_msginit,
};

static const upb_msglayout_field google_protobuf_OneofDescriptorProto__fields[2] = {
  {1, UPB_SIZE(4, 8), 1, 0, 12, 1},
  {2, UPB_SIZE(12, 24), 2, 0, 11, 1},
};

const upb_msglayout google_protobuf_OneofDescriptorProto_msginit = {
  &google_protobuf_OneofDescriptorProto_submsgs[0],
  &google_protobuf_OneofDescriptorProto__fields[0],
  UPB_SIZE(16, 32), 2, false, 2,
  {
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_pss_1bt, UPB_SIZE(562949953552394, 1688849860395018)},
    {&upb_psm_1bt_max64b, UPB_SIZE(2814827076517906, 6192526797045778)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
  },
};

static const upb_msglayout *const google_protobuf_EnumDescriptorProto_submsgs[3] = {
  &google_protobuf_EnumDescriptorProto_EnumReservedRange_msginit,
  &google_protobuf_EnumOptions_msginit,
  &google_protobuf_EnumValueDescriptorProto_msginit,
};

static const upb_msglayout_field google_protobuf_EnumDescriptorProto__fields[5] = {
  {1, UPB_SIZE(4, 8), 1, 0, 12, 1},
  {2, UPB_SIZE(16, 32), 0, 2, 11, 3},
  {3, UPB_SIZE(12, 24), 2, 1, 11, 1},
  {4, UPB_SIZE(20, 40), 0, 0, 11, 3},
  {5, UPB_SIZE(24, 48), 0, 0, 12, 3},
};

const upb_msglayout google_protobuf_EnumDescriptorProto_msginit = {
  &google_protobuf_EnumDescriptorProto_submsgs[0],
  &google_protobuf_EnumDescriptorProto__fields[0],
  UPB_SIZE(32, 64), 5, false, 3,
  {
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_pss_1bt, UPB_SIZE(281474976841738, 1407374883684362)},
    {&upb_prm_1bt_max64b, UPB_SIZE(3659174697369618, 8162774324740114)},
    {&upb_psm_1bt_max64b, UPB_SIZE(2533352099872794, 5911051820400666)},
    {&upb_prm_1bt_max64b, UPB_SIZE(4785074604081186, 10414574138294306)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
  },
};

static const upb_msglayout_field google_protobuf_EnumDescriptorProto_EnumReservedRange__fields[2] = {
  {1, UPB_SIZE(4, 4), 1, 0, 5, 1},
  {2, UPB_SIZE(8, 8), 2, 0, 5, 1},
};

const upb_msglayout google_protobuf_EnumDescriptorProto_EnumReservedRange_msginit = {
  NULL,
  &google_protobuf_EnumDescriptorProto_EnumReservedRange__fields[0],
  UPB_SIZE(16, 16), 2, false, 2,
  {
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_psv4_1bt, UPB_SIZE(562949953552392, 562949953552392)},
    {&upb_psv4_1bt, UPB_SIZE(1688849860526096, 1688849860526096)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
  },
};

static const upb_msglayout *const google_protobuf_EnumValueDescriptorProto_submsgs[1] = {
  &google_protobuf_EnumValueOptions_msginit,
};

static const upb_msglayout_field google_protobuf_EnumValueDescriptorProto__fields[3] = {
  {1, UPB_SIZE(8, 8), 2, 0, 12, 1},
  {2, UPB_SIZE(4, 4), 1, 0, 5, 1},
  {3, UPB_SIZE(16, 24), 3, 0, 11, 1},
};

const upb_msglayout google_protobuf_EnumValueDescriptorProto_msginit = {
  &google_protobuf_EnumValueDescriptorProto_submsgs[0],
  &google_protobuf_EnumValueDescriptorProto__fields[0],
  UPB_SIZE(24, 32), 3, false, 2,
  {
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_pss_1bt, UPB_SIZE(1688849860526090, 1688849860526090)},
    {&upb_psv4_1bt, UPB_SIZE(562949953552400, 562949953552400)},
    {&upb_psm_1bt_max64b, UPB_SIZE(3940731278327834, 6192531092013082)},
  },
};

static const upb_msglayout *const google_protobuf_ServiceDescriptorProto_submsgs[2] = {
  &google_protobuf_MethodDescriptorProto_msginit,
  &google_protobuf_ServiceOptions_msginit,
};

static const upb_msglayout_field google_protobuf_ServiceDescriptorProto__fields[3] = {
  {1, UPB_SIZE(4, 8), 1, 0, 12, 1},
  {2, UPB_SIZE(16, 32), 0, 0, 11, 3},
  {3, UPB_SIZE(12, 24), 2, 1, 11, 1},
};

const upb_msglayout google_protobuf_ServiceDescriptorProto_msginit = {
  &google_protobuf_ServiceDescriptorProto_submsgs[0],
  &google_protobuf_ServiceDescriptorProto__fields[0],
  UPB_SIZE(24, 48), 3, false, 2,
  {
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_pss_1bt, UPB_SIZE(562949953552394, 1688849860395018)},
    {&upb_prm_1bt_max128b, UPB_SIZE(3940649673949202, 8444249301319698)},
    {&upb_psm_1bt_max64b, UPB_SIZE(2814827076583450, 6192526797111322)},
  },
};

static const upb_msglayout *const google_protobuf_MethodDescriptorProto_submsgs[1] = {
  &google_protobuf_MethodOptions_msginit,
};

static const upb_msglayout_field google_protobuf_MethodDescriptorProto__fields[6] = {
  {1, UPB_SIZE(4, 8), 3, 0, 12, 1},
  {2, UPB_SIZE(12, 24), 4, 0, 12, 1},
  {3, UPB_SIZE(20, 40), 5, 0, 12, 1},
  {4, UPB_SIZE(28, 56), 6, 0, 11, 1},
  {5, UPB_SIZE(1, 1), 1, 0, 8, 1},
  {6, UPB_SIZE(2, 2), 2, 0, 8, 1},
};

const upb_msglayout google_protobuf_MethodDescriptorProto_msginit = {
  &google_protobuf_MethodDescriptorProto_submsgs[0],
  &google_protobuf_MethodDescriptorProto__fields[0],
  UPB_SIZE(32, 64), 6, false, 3,
  {
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_pss_1bt, UPB_SIZE(281474977234954, 1407374884077578)},
    {&upb_pss_1bt, UPB_SIZE(2533274791444498, 5910974511972370)},
    {&upb_pss_1bt, UPB_SIZE(4785074606178330, 10414574140391450)},
    {&upb_psm_1bt_max64b, UPB_SIZE(7036968907046946, 14918268254945314)},
    {&upb_psb1_1bt, UPB_SIZE(-562949953290200, -562949953290200)},
    {&upb_psb1_1bt, UPB_SIZE(-281474976448464, -281474976448464)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
  },
};

static const upb_msglayout *const google_protobuf_FileOptions_submsgs[1] = {
  &google_protobuf_UninterpretedOption_msginit,
};

static const upb_msglayout_field google_protobuf_FileOptions__fields[21] = {
  {1, UPB_SIZE(28, 32), 11, 0, 12, 1},
  {8, UPB_SIZE(36, 48), 12, 0, 12, 1},
  {9, UPB_SIZE(8, 8), 1, 0, 14, 1},
  {10, UPB_SIZE(16, 16), 2, 0, 8, 1},
  {11, UPB_SIZE(44, 64), 13, 0, 12, 1},
  {16, UPB_SIZE(17, 17), 3, 0, 8, 1},
  {17, UPB_SIZE(18, 18), 4, 0, 8, 1},
  {18, UPB_SIZE(19, 19), 5, 0, 8, 1},
  {20, UPB_SIZE(20, 20), 6, 0, 8, 1},
  {23, UPB_SIZE(21, 21), 7, 0, 8, 1},
  {27, UPB_SIZE(22, 22), 8, 0, 8, 1},
  {31, UPB_SIZE(23, 23), 9, 0, 8, 1},
  {36, UPB_SIZE(52, 80), 14, 0, 12, 1},
  {37, UPB_SIZE(60, 96), 15, 0, 12, 1},
  {39, UPB_SIZE(68, 112), 16, 0, 12, 1},
  {40, UPB_SIZE(76, 128), 17, 0, 12, 1},
  {41, UPB_SIZE(84, 144), 18, 0, 12, 1},
  {42, UPB_SIZE(24, 24), 10, 0, 8, 1},
  {44, UPB_SIZE(92, 160), 19, 0, 12, 1},
  {45, UPB_SIZE(100, 176), 20, 0, 12, 1},
  {999, UPB_SIZE(108, 192), 0, 0, 11, 3},
};

const upb_msglayout google_protobuf_FileOptions_msginit = {
  &google_protobuf_FileOptions_submsgs[0],
  &google_protobuf_FileOptions__fields[0],
  UPB_SIZE(112, 208), 21, false, 5,
  {
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_pss_1bt, UPB_SIZE(6473924598562826, 7599824505405450)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_pss_1bt, UPB_SIZE(8725724546465858, 12103424266993730)},
    {&upb_psv4_1bt, UPB_SIZE(844424930263112, 844424930263112)},
    {&upb_psb1_1bt, UPB_SIZE(3096224744079440, 3096224744079440)},
    {&upb_pss_1bt, UPB_SIZE(10977524628586586, 16607024162799706)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_psb1_2bt, UPB_SIZE(3377699721052544, 3377699721052544)},
    {&upb_psb1_2bt, UPB_SIZE(3659174698287496, 3659174698287496)},
    {&upb_psb1_2bt, UPB_SIZE(3940649676046736, 3940649676046736)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_psb1_2bt, UPB_SIZE(4222124654854560, 4222124654854560)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_psb1_2bt, UPB_SIZE(4503599635759544, 4503599635759544)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_psb1_2bt, UPB_SIZE(4785074620858840, 4785074620858840)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_psb1_2bt, UPB_SIZE(5066549614346744, 5066549614346744)},
  },
};

static const upb_msglayout *const google_protobuf_MessageOptions_submsgs[1] = {
  &google_protobuf_UninterpretedOption_msginit,
};

static const upb_msglayout_field google_protobuf_MessageOptions__fields[5] = {
  {1, UPB_SIZE(1, 1), 1, 0, 8, 1},
  {2, UPB_SIZE(2, 2), 2, 0, 8, 1},
  {3, UPB_SIZE(3, 3), 3, 0, 8, 1},
  {7, UPB_SIZE(4, 4), 4, 0, 8, 1},
  {999, UPB_SIZE(8, 8), 0, 0, 11, 3},
};

const upb_msglayout google_protobuf_MessageOptions_msginit = {
  &google_protobuf_MessageOptions_submsgs[0],
  &google_protobuf_MessageOptions__fields[0],
  UPB_SIZE(16, 16), 5, false, 3,
  {
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_psb1_1bt, UPB_SIZE(-562949953290232, -562949953290232)},
    {&upb_psb1_1bt, UPB_SIZE(-281474976448496, -281474976448496)},
    {&upb_psb1_1bt, UPB_SIZE(524312, 524312)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_psb1_1bt, UPB_SIZE(281474977759288, 281474977759288)},
  },
};

static const upb_msglayout *const google_protobuf_FieldOptions_submsgs[1] = {
  &google_protobuf_UninterpretedOption_msginit,
};

static const upb_msglayout_field google_protobuf_FieldOptions__fields[7] = {
  {1, UPB_SIZE(8, 8), 1, 0, 14, 1},
  {2, UPB_SIZE(24, 24), 3, 0, 8, 1},
  {3, UPB_SIZE(25, 25), 4, 0, 8, 1},
  {5, UPB_SIZE(26, 26), 5, 0, 8, 1},
  {6, UPB_SIZE(16, 16), 2, 0, 14, 1},
  {10, UPB_SIZE(27, 27), 6, 0, 8, 1},
  {999, UPB_SIZE(28, 32), 0, 0, 11, 3},
};

const upb_msglayout google_protobuf_FieldOptions_msginit = {
  &google_protobuf_FieldOptions_submsgs[0],
  &google_protobuf_FieldOptions__fields[0],
  UPB_SIZE(32, 40), 7, false, 4,
  {
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_psv4_1bt, UPB_SIZE(1125899906973704, 1125899906973704)},
    {&upb_psb1_1bt, UPB_SIZE(5629499534737424, 5629499534737424)},
    {&upb_psb1_1bt, UPB_SIZE(5910974511972376, 5910974511972376)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_psb1_1bt, UPB_SIZE(6192449489731624, 6192449489731624)},
    {&upb_psv4_1bt, UPB_SIZE(3377699720790064, 3377699720790064)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_psb1_1bt, UPB_SIZE(6473924468539472, 6473924468539472)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
  },
};

static const upb_msglayout *const google_protobuf_OneofOptions_submsgs[1] = {
  &google_protobuf_UninterpretedOption_msginit,
};

static const upb_msglayout_field google_protobuf_OneofOptions__fields[1] = {
  {999, UPB_SIZE(0, 0), 0, 0, 11, 3},
};

const upb_msglayout google_protobuf_OneofOptions_msginit = {
  &google_protobuf_OneofOptions_submsgs[0],
  &google_protobuf_OneofOptions__fields[0],
  UPB_SIZE(8, 8), 1, false, 0,
  {
    {&fastdecode_generic, UPB_SIZE(0, 0)},
  },
};

static const upb_msglayout *const google_protobuf_EnumOptions_submsgs[1] = {
  &google_protobuf_UninterpretedOption_msginit,
};

static const upb_msglayout_field google_protobuf_EnumOptions__fields[3] = {
  {2, UPB_SIZE(1, 1), 1, 0, 8, 1},
  {3, UPB_SIZE(2, 2), 2, 0, 8, 1},
  {999, UPB_SIZE(4, 8), 0, 0, 11, 3},
};

const upb_msglayout google_protobuf_EnumOptions_msginit = {
  &google_protobuf_EnumOptions_submsgs[0],
  &google_protobuf_EnumOptions__fields[0],
  UPB_SIZE(8, 16), 3, false, 2,
  {
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_psb1_1bt, UPB_SIZE(-281474976579568, -281474976579568)},
    {&upb_psb1_1bt, UPB_SIZE(262168, 262168)},
  },
};

static const upb_msglayout *const google_protobuf_EnumValueOptions_submsgs[1] = {
  &google_protobuf_UninterpretedOption_msginit,
};

static const upb_msglayout_field google_protobuf_EnumValueOptions__fields[2] = {
  {1, UPB_SIZE(1, 1), 1, 0, 8, 1},
  {999, UPB_SIZE(4, 8), 0, 0, 11, 3},
};

const upb_msglayout google_protobuf_EnumValueOptions_msginit = {
  &google_protobuf_EnumValueOptions_submsgs[0],
  &google_protobuf_EnumValueOptions__fields[0],
  UPB_SIZE(8, 16), 2, false, 1,
  {
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_psb1_1bt, UPB_SIZE(131080, 131080)},
  },
};

static const upb_msglayout *const google_protobuf_ServiceOptions_submsgs[1] = {
  &google_protobuf_UninterpretedOption_msginit,
};

static const upb_msglayout_field google_protobuf_ServiceOptions__fields[2] = {
  {33, UPB_SIZE(1, 1), 1, 0, 8, 1},
  {999, UPB_SIZE(4, 8), 0, 0, 11, 3},
};

const upb_msglayout google_protobuf_ServiceOptions_msginit = {
  &google_protobuf_ServiceOptions_submsgs[0],
  &google_protobuf_ServiceOptions__fields[0],
  UPB_SIZE(8, 16), 2, false, 0,
  {
    {&fastdecode_generic, UPB_SIZE(0, 0)},
  },
};

static const upb_msglayout *const google_protobuf_MethodOptions_submsgs[1] = {
  &google_protobuf_UninterpretedOption_msginit,
};

static const upb_msglayout_field google_protobuf_MethodOptions__fields[3] = {
  {33, UPB_SIZE(16, 16), 2, 0, 8, 1},
  {34, UPB_SIZE(8, 8), 1, 0, 14, 1},
  {999, UPB_SIZE(20, 24), 0, 0, 11, 3},
};

const upb_msglayout google_protobuf_MethodOptions_msginit = {
  &google_protobuf_MethodOptions_submsgs[0],
  &google_protobuf_MethodOptions__fields[0],
  UPB_SIZE(24, 32), 3, false, 0,
  {
    {&fastdecode_generic, UPB_SIZE(0, 0)},
  },
};

static const upb_msglayout *const google_protobuf_UninterpretedOption_submsgs[1] = {
  &google_protobuf_UninterpretedOption_NamePart_msginit,
};

static const upb_msglayout_field google_protobuf_UninterpretedOption__fields[7] = {
  {2, UPB_SIZE(56, 80), 0, 0, 11, 3},
  {3, UPB_SIZE(32, 32), 4, 0, 12, 1},
  {4, UPB_SIZE(8, 8), 1, 0, 4, 1},
  {5, UPB_SIZE(16, 16), 2, 0, 3, 1},
  {6, UPB_SIZE(24, 24), 3, 0, 1, 1},
  {7, UPB_SIZE(40, 48), 5, 0, 12, 1},
  {8, UPB_SIZE(48, 64), 6, 0, 12, 1},
};

const upb_msglayout google_protobuf_UninterpretedOption_msginit = {
  &google_protobuf_UninterpretedOption_submsgs[0],
  &google_protobuf_UninterpretedOption__fields[0],
  UPB_SIZE(64, 96), 7, false, 4,
  {
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_prm_1bt_max64b, UPB_SIZE(14636698788954130, 21392098230009874)},
    {&upb_pss_1bt, UPB_SIZE(7881299348946970, 7881299348946970)},
    {&upb_psv8_1bt, UPB_SIZE(1125899906973728, 1125899906973728)},
    {&upb_psv8_1bt, UPB_SIZE(3377699720790056, 3377699720790056)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_pss_1bt, UPB_SIZE(10133099163680826, 12384898977366074)},
    {&upb_pss_1bt, UPB_SIZE(12384898979463234, 16888498606833730)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
  },
};

static const upb_msglayout_field google_protobuf_UninterpretedOption_NamePart__fields[2] = {
  {1, UPB_SIZE(4, 8), 2, 0, 12, 2},
  {2, UPB_SIZE(1, 1), 1, 0, 8, 2},
};

const upb_msglayout google_protobuf_UninterpretedOption_NamePart_msginit = {
  NULL,
  &google_protobuf_UninterpretedOption_NamePart__fields[0],
  UPB_SIZE(16, 32), 2, false, 2,
  {
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_pss_1bt, UPB_SIZE(562949953683466, 1688849860526090)},
    {&upb_psb1_1bt, UPB_SIZE(-281474976579568, -281474976579568)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
  },
};

static const upb_msglayout *const google_protobuf_SourceCodeInfo_submsgs[1] = {
  &google_protobuf_SourceCodeInfo_Location_msginit,
};

static const upb_msglayout_field google_protobuf_SourceCodeInfo__fields[1] = {
  {1, UPB_SIZE(0, 0), 0, 0, 11, 3},
};

const upb_msglayout google_protobuf_SourceCodeInfo_msginit = {
  &google_protobuf_SourceCodeInfo_submsgs[0],
  &google_protobuf_SourceCodeInfo__fields[0],
  UPB_SIZE(8, 8), 1, false, 1,
  {
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_prm_1bt_max128b, UPB_SIZE(-281474976710646, -281474976710646)},
  },
};

static const upb_msglayout_field google_protobuf_SourceCodeInfo_Location__fields[5] = {
  {1, UPB_SIZE(20, 40), 0, 0, 5, _UPB_LABEL_PACKED},
  {2, UPB_SIZE(24, 48), 0, 0, 5, _UPB_LABEL_PACKED},
  {3, UPB_SIZE(4, 8), 1, 0, 12, 1},
  {4, UPB_SIZE(12, 24), 2, 0, 12, 1},
  {6, UPB_SIZE(28, 56), 0, 0, 12, 3},
};

const upb_msglayout google_protobuf_SourceCodeInfo_Location_msginit = {
  NULL,
  &google_protobuf_SourceCodeInfo_Location__fields[0],
  UPB_SIZE(32, 64), 5, false, 3,
  {
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_pss_1bt, UPB_SIZE(281474976841754, 1407374883684378)},
    {&upb_pss_1bt, UPB_SIZE(2533274790658082, 5910974511185954)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
  },
};

static const upb_msglayout *const google_protobuf_GeneratedCodeInfo_submsgs[1] = {
  &google_protobuf_GeneratedCodeInfo_Annotation_msginit,
};

static const upb_msglayout_field google_protobuf_GeneratedCodeInfo__fields[1] = {
  {1, UPB_SIZE(0, 0), 0, 0, 11, 3},
};

const upb_msglayout google_protobuf_GeneratedCodeInfo_msginit = {
  &google_protobuf_GeneratedCodeInfo_submsgs[0],
  &google_protobuf_GeneratedCodeInfo__fields[0],
  UPB_SIZE(8, 8), 1, false, 1,
  {
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_prm_1bt_max64b, UPB_SIZE(-281474976710646, -281474976710646)},
  },
};

static const upb_msglayout_field google_protobuf_GeneratedCodeInfo_Annotation__fields[4] = {
  {1, UPB_SIZE(20, 32), 0, 0, 5, _UPB_LABEL_PACKED},
  {2, UPB_SIZE(12, 16), 3, 0, 12, 1},
  {3, UPB_SIZE(4, 4), 1, 0, 5, 1},
  {4, UPB_SIZE(8, 8), 2, 0, 5, 1},
};

const upb_msglayout google_protobuf_GeneratedCodeInfo_Annotation_msginit = {
  NULL,
  &google_protobuf_GeneratedCodeInfo_Annotation__fields[0],
  UPB_SIZE(24, 48), 4, false, 3,
  {
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&upb_pss_1bt, UPB_SIZE(2533274790920210, 3659174697762834)},
    {&upb_psv4_1bt, UPB_SIZE(281474976841752, 281474976841752)},
    {&upb_psv4_1bt, UPB_SIZE(1407374883815456, 1407374883815456)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
    {&fastdecode_generic, UPB_SIZE(0, 0)},
  },
};

#include "upb/port_undef.inc"

